language: node_js
node_js:
  - 10.1.0
cache: npm
deploy:
  - provider: script
    skip_cleanup: true
    script: git checkout master && npm run update -- --token $GH_TOKEN --auto
    'on':
      branch: master
